In [2]:
import numpy as np

In [4]:
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
a.shape

(3, 4)

In [8]:
a.size

12

In [9]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [17]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1.0, 10.0, 2.0)

array([1., 3., 5., 7., 9.])

In [24]:
np.linspace(0, 5/3, 6)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

In [25]:
np.random.rand(3,4)

array([[0.99183322, 0.64835673, 0.42743694, 0.25337497],
       [0.20870612, 0.85459251, 0.25011619, 0.2241852 ],
       [0.37810095, 0.50214501, 0.12643602, 0.9518667 ]])

In [27]:
np.random.randn(3, 4)

array([[-1.2518129 , -2.294167  , -0.25690742,  0.35291572],
       [ 0.52507484, -0.10723392,  1.65318109, -0.06985278],
       [-0.12145193,  0.4373173 , -1.79046622,  1.45570141]])

In [28]:
import matplotlib.pyplot as plt